### ISSUE TITLE
dtbs_install broken

### ISSUE THREAD

**Issue by jan-kiszka** [OE4T/linux-tegra-5.10#2]
Might be due to the unfolding of the source tree overlays. I've worked around it like this:

```
diff --git a/scripts/Makefile.dtbinst b/scripts/Makefile.dtbinst
index 50d580d77ae9..f69eb7bb63fb 100644
--- a/scripts/Makefile.dtbinst
+++ b/scripts/Makefile.dtbinst
@@ -17,7 +17,7 @@ include include/config/auto.conf
 include scripts/Kbuild.include
 include $(src)/Makefile
 
-dtbs    := $(addprefix $(dst)/, $(dtb-y) $(if $(CONFIG_OF_ALL_DTBS),$(dtb-)))
+dtbs    := $(addprefix $(dst)/, $(notdir $(dtb-y)) $(if $(CONFIG_OF_ALL_DTBS),$(dtb-)))
 subdirs := $(addprefix $(obj)/, $(subdir-y) $(subdir-m))
 
 __dtbs_install: $(dtbs) $(subdirs)
```

Maybe there is a slightly nicer solution as well.

**Comment by madisongh** [comment]
Thanks.  At first glance, that looks like the right fix, but I'll take a closer look when I get a chance.

**Comment by madisongh** [comment]
I incorporated that change when importing the sources for the L4T R35.1.0 (GA release) kernel.  Give it a try on the `oe4t-patches-l4t-r35.1` branch (which is now the default).

**Comment by jan-kiszka** [comment]
Looks good, thanks.
